"""Floor and Workspace Tables Modified

Revision ID: 0cbeedd73816
Revises: 700b87d4bce7
Create Date: 2026-04-30 13:24:48.806081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbeedd73816'
down_revision: Union[str, Sequence[str], None] = '700b87d4bce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Floor_Table', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_Floor_Table_floor_number'), table_name='Floor_Table')
    op.create_index(op.f('ix_Floor_Table_floor_number'), 'Floor_Table', ['floor_number'], unique=True)
    op.add_column('Workspace_Table', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('Workspace_Table', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'Workspace_Table', ['workspace_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Workspace_Table', type_='unique')
    op.drop_column('Workspace_Table', 'is_deleted')
    op.drop_column('Workspace_Table', 'created_at')
    op.drop_index(op.f('ix_Floor_Table_floor_number'), table_name='Floor_Table')
    op.create_index(op.f('ix_Floor_Table_floor_number'), 'Floor_Table', ['floor_number'], unique=False)
    op.drop_column('Floor_Table', 'is_deleted')
    # ### end Alembic commands ###
