"""Minor Tabular Chnages

Revision ID: 1d80f1f976d0
Revises: c61ecbdee489
Create Date: 2026-05-04 16:04:28.435244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d80f1f976d0'
down_revision: Union[str, Sequence[str], None] = 'c61ecbdee489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Floor_Table', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.drop_column('Floor_Table', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Floor_Table', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Floor_Table', 'is_available')
    # ### end Alembic commands ###
