"""Few Minor Changes in Resource Table and others

Revision ID: 2bee7f7683ac
Revises: c3ba16020024
Create Date: 2026-05-05 16:15:42.751102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bee7f7683ac'
down_revision: Union[str, Sequence[str], None] = 'c3ba16020024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Booking_Table', sa.Column('floor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'Booking_Table', 'Floor_Table', ['floor_id'], ['floor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Booking_Table', type_='foreignkey')
    op.drop_column('Booking_Table', 'floor_id')
    # ### end Alembic commands ###
