"""Payments Table and its relationship Added

Revision ID: 2f79eb17b770
Revises: 3b08e712c1c4
Create Date: 2026-05-08 11:24:52.149203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79eb17b770'
down_revision: Union[str, Sequence[str], None] = '3b08e712c1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payment_Table',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('COMPLETED', 'PENDING', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['Booking_Table.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payment_Table')
    # ### end Alembic commands ###
