"""Price_Per_Hour Column Added as part of the Payments Component of the project in the Resources Table

Revision ID: 3544805f2edf
Revises: cd2e245f46d0
Create Date: 2026-05-07 16:35:12.039851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3544805f2edf'
down_revision: Union[str, Sequence[str], None] = 'cd2e245f46d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resource_Table', sa.Column('price_per_booking', sa.Integer(), server_default='500', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resource_Table', 'price_per_booking')
    # ### end Alembic commands ###
