"""Floor and Workspace Tables Added Again

Revision ID: 700b87d4bce7
Revises: 46d07f0da058
Create Date: 2026-04-30 12:47:09.627171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700b87d4bce7'
down_revision: Union[str, Sequence[str], None] = '46d07f0da058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workspace_Table',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('workspace_name', sa.String(), nullable=False),
    sa.Column('workspace_location', sa.String(), nullable=False),
    sa.Column('workspace_manager_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_manager_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_Workspace_Table_workspace_location'), 'Workspace_Table', ['workspace_location'], unique=False)
    op.create_table('Floor_Table',
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['Workspace_Table.workspace_id'], ),
    sa.PrimaryKeyConstraint('floor_id')
    )
    op.create_index(op.f('ix_Floor_Table_floor_number'), 'Floor_Table', ['floor_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Floor_Table_floor_number'), table_name='Floor_Table')
    op.drop_table('Floor_Table')
    op.drop_index(op.f('ix_Workspace_Table_workspace_location'), table_name='Workspace_Table')
    op.drop_table('Workspace_Table')
    # ### end Alembic commands ###
