"""Major Tabular Changes

Revision ID: 8818022d0eb6
Revises: 8ca4de954113
Create Date: 2026-05-04 13:40:33.910660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8818022d0eb6'
down_revision: Union[str, Sequence[str], None] = '8ca4de954113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Floor_Table', sa.Column('floor_meeting_room_capacity', sa.Integer(), server_default='7', nullable=True))
    op.add_column('Floor_Table', sa.Column('floor_auditorium_capacity', sa.Integer(), server_default='3', nullable=True))
    op.add_column('Resource_Table', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('Resource_Table', sa.Column('open_time', sa.Time(), server_default='06:30:00', nullable=False))
    op.add_column('Resource_Table', sa.Column('close_time', sa.Time(), server_default='22:30:00', nullable=False))
    op.add_column('Workspace_Table', sa.Column('workspace_floor_capacity', sa.Integer(), server_default='10', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workspace_Table', 'workspace_floor_capacity')
    op.drop_column('Resource_Table', 'close_time')
    op.drop_column('Resource_Table', 'open_time')
    op.drop_column('Resource_Table', 'requires_approval')
    op.drop_column('Floor_Table', 'floor_auditorium_capacity')
    op.drop_column('Floor_Table', 'floor_meeting_room_capacity')
    # ### end Alembic commands ###
