"""Resource Table added and User Table Modified

Revision ID: 8ca4de954113
Revises: d98aa0688f5b
Create Date: 2026-04-30 16:55:00.136956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca4de954113'
down_revision: Union[str, Sequence[str], None] = 'd98aa0688f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resource_Table',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('MEETING_ROOM', 'AUDITORIUMN', name='resourcetype'), nullable=True),
    sa.Column('resource_capacity', sa.Integer(), nullable=False),
    sa.Column('is_avaialable', sa.Boolean(), nullable=True),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['Floor_Table.floor_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resource_Table')
    # ### end Alembic commands ###
