"""BookingResource Table Created

Revision ID: 8fdfd24577b3
Revises: 2bee7f7683ac
Create Date: 2026-05-06 11:12:54.755259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fdfd24577b3'
down_revision: Union[str, Sequence[str], None] = '2bee7f7683ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Booking_Table', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="booking_date + start_time")
    op.alter_column('Booking_Table', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="booking_date + end_time")
    op.drop_constraint(op.f('Booking_Table_resource_id_fkey'), 'Booking_Table', type_='foreignkey')
    op.drop_column('Booking_Table', 'booking_date')
    op.drop_column('Booking_Table', 'resource_id')
    op.drop_column('Resource_Table', 'is_avaialable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resource_Table', sa.Column('is_avaialable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Booking_Table', sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Booking_Table', sa.Column('booking_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('Booking_Table_resource_id_fkey'), 'Booking_Table', 'Resource_Table', ['resource_id'], ['resource_id'])
    op.alter_column('Booking_Table', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('Booking_Table', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
