"""Minor Changes in Floor Table and others

Revision ID: 934e5b9a5c9f
Revises: 1d80f1f976d0
Create Date: 2026-05-05 12:05:16.164598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934e5b9a5c9f'
down_revision: Union[str, Sequence[str], None] = '1d80f1f976d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Floor_Table', sa.Column('total_floor_meeting_room_capacity', sa.Integer(), server_default='7', nullable=True))
    op.add_column('Floor_Table', sa.Column('available_floor_meeting_room_capacity', sa.Integer(), server_default='7', nullable=True))
    op.add_column('Floor_Table', sa.Column('total_floor_auditorium_capacity', sa.Integer(), server_default='7', nullable=True))
    op.add_column('Floor_Table', sa.Column('avaialable_floor_auditorium_capacity', sa.Integer(), server_default='3', nullable=True))
    op.drop_column('Floor_Table', 'floor_meeting_room_capacity')
    op.drop_column('Floor_Table', 'floor_auditorium_capacity')
    op.add_column('Resource_Table', sa.Column('total_resource_capacity', sa.Integer(), nullable=False))
    op.add_column('Resource_Table', sa.Column('available_resource_capacity', sa.Integer(), nullable=False))
    op.drop_column('Resource_Table', 'resource_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resource_Table', sa.Column('resource_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Resource_Table', 'available_resource_capacity')
    op.drop_column('Resource_Table', 'total_resource_capacity')
    op.add_column('Floor_Table', sa.Column('floor_auditorium_capacity', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True))
    op.add_column('Floor_Table', sa.Column('floor_meeting_room_capacity', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=True))
    op.drop_column('Floor_Table', 'avaialable_floor_auditorium_capacity')
    op.drop_column('Floor_Table', 'total_floor_auditorium_capacity')
    op.drop_column('Floor_Table', 'available_floor_meeting_room_capacity')
    op.drop_column('Floor_Table', 'total_floor_meeting_room_capacity')
    # ### end Alembic commands ###
