"""Updated User Table

Revision ID: adb9d5d62761
Revises: 91b55869eecf
Create Date: 2026-04-30 11:55:19.255638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb9d5d62761'
down_revision: Union[str, Sequence[str], None] = '91b55869eecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Table', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('User_Table', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_User_Table_user_email'), 'User_Table', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Table_user_email'), table_name='User_Table')
    op.drop_column('User_Table', 'is_deleted')
    op.drop_column('User_Table', 'updated_at')
    # ### end Alembic commands ###
