"""Booking and Booking Resource Table Modified

Revision ID: b387c7e162ad
Revises: e52677b021e8
Create Date: 2026-05-06 15:21:15.236385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b387c7e162ad'
down_revision: Union[str, Sequence[str], None] = 'e52677b021e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookingResource_Table', sa.Column('floor_id', sa.UUID(), nullable=True))
    op.add_column('BookingResource_Table', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'BookingResource_Table', 'Workspace_Table', ['workspace_id'], ['workspace_id'])
    op.create_foreign_key(None, 'BookingResource_Table', 'Floor_Table', ['floor_id'], ['floor_id'])
    op.drop_constraint(op.f('Booking_Table_floor_id_fkey'), 'Booking_Table', type_='foreignkey')
    op.drop_constraint(op.f('Booking_Table_workspace_id_fkey'), 'Booking_Table', type_='foreignkey')
    op.drop_column('Booking_Table', 'floor_id')
    op.drop_column('Booking_Table', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Booking_Table', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Booking_Table', sa.Column('floor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Booking_Table_workspace_id_fkey'), 'Booking_Table', 'Workspace_Table', ['workspace_id'], ['workspace_id'])
    op.create_foreign_key(op.f('Booking_Table_floor_id_fkey'), 'Booking_Table', 'Floor_Table', ['floor_id'], ['floor_id'])
    op.drop_constraint(None, 'BookingResource_Table', type_='foreignkey')
    op.drop_constraint(None, 'BookingResource_Table', type_='foreignkey')
    op.drop_column('BookingResource_Table', 'workspace_id')
    op.drop_column('BookingResource_Table', 'floor_id')
    # ### end Alembic commands ###
