"""Few Minor Changes in Resource Table and others

Revision ID: c3ba16020024
Revises: 934e5b9a5c9f
Create Date: 2026-05-05 15:11:55.135913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ba16020024'
down_revision: Union[str, Sequence[str], None] = '934e5b9a5c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
