"""Booking table added and Major Tabular Changes

Revision ID: c61ecbdee489
Revises: eb9d41db7a5e
Create Date: 2026-05-04 15:01:42.311272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61ecbdee489'
down_revision: Union[str, Sequence[str], None] = 'eb9d41db7a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Booking_Table',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('booking_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='bookingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource_Table.resource_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['Workspace_Table.workspace_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Booking_Table')
    # ### end Alembic commands ###
