"""Added created_at in Booking and Booking Resource Table

Revision ID: cd2e245f46d0
Revises: b387c7e162ad
Create Date: 2026-05-06 16:49:55.922691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2e245f46d0'
down_revision: Union[str, Sequence[str], None] = 'b387c7e162ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BookingResource_Table', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Booking_Table', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Booking_Table', 'created_at')
    op.drop_column('BookingResource_Table', 'created_at')
    # ### end Alembic commands ###
