"""Creating BookingResource Table

Revision ID: d4215700ea38
Revises: 8fdfd24577b3
Create Date: 2026-05-06 11:25:56.761085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4215700ea38'
down_revision: Union[str, Sequence[str], None] = '8fdfd24577b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookingResource_Table',
    sa.Column('bookingresource_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['Booking_Table.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource_Table.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookingresource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookingResource_Table')
    # ### end Alembic commands ###
