"""Resource Table added and User Table Modified

Revision ID: d98aa0688f5b
Revises: f04e0a234f44
Create Date: 2026-04-30 16:53:45.023288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98aa0688f5b'
down_revision: Union[str, Sequence[str], None] = 'f04e0a234f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
