"""Cascading added to resource table

Revision ID: e52677b021e8
Revises: d4215700ea38
Create Date: 2026-05-06 14:04:44.546706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52677b021e8'
down_revision: Union[str, Sequence[str], None] = 'd4215700ea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Floor_Table_workspace_id_fkey'), 'Floor_Table', type_='foreignkey')
    op.create_foreign_key(None, 'Floor_Table', 'Workspace_Table', ['workspace_id'], ['workspace_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('Resource_Table_floor_id_fkey'), 'Resource_Table', type_='foreignkey')
    op.create_foreign_key(None, 'Resource_Table', 'Floor_Table', ['floor_id'], ['floor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Resource_Table', type_='foreignkey')
    op.create_foreign_key(op.f('Resource_Table_floor_id_fkey'), 'Resource_Table', 'Floor_Table', ['floor_id'], ['floor_id'])
    op.drop_constraint(None, 'Floor_Table', type_='foreignkey')
    op.create_foreign_key(op.f('Floor_Table_workspace_id_fkey'), 'Floor_Table', 'Workspace_Table', ['workspace_id'], ['workspace_id'])
    # ### end Alembic commands ###
