"""Booking table added and Major Tabular Changes

Revision ID: eb9d41db7a5e
Revises: 8818022d0eb6
Create Date: 2026-05-04 14:57:44.630051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9d41db7a5e'
down_revision: Union[str, Sequence[str], None] = '8818022d0eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resource_Table', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resource_Table', 'is_deleted')
    # ### end Alembic commands ###
