"""Floor Table Modified

Revision ID: f04e0a234f44
Revises: 0cbeedd73816
Create Date: 2026-04-30 15:04:17.012595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04e0a234f44'
down_revision: Union[str, Sequence[str], None] = '0cbeedd73816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Floor_Table_floor_number'), table_name='Floor_Table')
    op.create_index(op.f('ix_Floor_Table_floor_number'), 'Floor_Table', ['floor_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Floor_Table_floor_number'), table_name='Floor_Table')
    op.create_index(op.f('ix_Floor_Table_floor_number'), 'Floor_Table', ['floor_number'], unique=True)
    # ### end Alembic commands ###
